# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RunningNote' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pod for RunningNote
    pod 'AFNetworking', '~> 3.1.0'
    pod 'FMDB', '~> 2.6.2'
    pod 'Masonry', '~> 1.0.1'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'HIPImageCropper', '~> 2.0.0'
  target 'RunningNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunningNoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
